0F 
                     01--09-=0B==0F= 0Awelcome to plop Linux 0F=0B==09=-01--0F
                08----01----09----0B----0F---------------0B----09----01----08----0F




07 "0Alinux07"    default boot after 10 seconds or press enter
07            use "copy2ram" if you want to remove the media. "0Alinux copy2ram07"
07            use "busybox" to start busybox before searching the boot device.
07 "0Alinuxfb07"  for framebuffer 1024x786 or use vga=0x315 for 800x600

07 "0Aplp07"      start plop boot manager 5.0
07 "0Aplpinst07"  start plop boot manager install program
07 "0Amemtest07"  start memtest
07 "0Ahd07"       boot first harddisk

07            read more at 0Ahttp://www.plop.at
                                                                 04€ﬂ€ €  ‹‹‹ €ﬂ€0F
                                                                 04€ﬂﬂ €€ €‹€ €ﬂﬂ07
